filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/book-mile/*.log
    fields:
      service: book-mile
    json.keys_under_root: false
    json.add_error_key: true

output.logstash:
  hosts: ["logstash:5044"]
