# New instance3
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Build and Push Docker Image
    - name: Build and Push Docker Image
      working-directory: ./
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/bookmile-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/bookmile-app:latest

    # .env 파일 생성
    - name: Create .env File
      run: |
        touch ./.env
        echo "${{ secrets.ENVIRONMENT }}" > ./.env

    # .env 내용
    - name: reading env file
      run: |
        cat ./.env
        ls ./
        
      # .gitignore에 있는 properties파일 추가
    - name: Add prod_properties
      run: |
        touch ./src/main/resources/application.properties
        touch ./src/main/resources/application-oauth.properties
        touch ./src/main/resources/application-private.properties
        echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
        echo "${{ secrets.OAUTHPROPERTIES }}" > ./src/main/resources/application-oauth.properties
        echo "${{ secrets.PRIVATEPROPERTIES }}" > ./src/main/resources/application-private.properties
        
    # Transfer Docker Compose File to EC2
    - name: Transfer Docker Compose to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: ./*
        target: ~/backend/

    # Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        debug: true
        script: |
          cd ~/backend
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bookmile-app:latest
          sudo docker-compose -f docker-compose.yml down
          sudo docker-compose -f docker-compose.yml up --build -d
